### ISSUE TITLE
Classes are not merged when using SSR

### ISSUE THREAD

**Issue by lejtzen** [brandonpittman/gridsome-plugin-svg#4]
If you add classes to the "imported inline SVG component" they will not be merged when rendered using SSR.

Looks like it was solved in vue-svg-loader 0.15.0 [https://github.com/visualfanatic/vue-svg-loader/issues/94](https://github.com/visualfanatic/vue-svg-loader/issues/94).

Would it be possible to bump the version of vue-svg-loader? 😃

**Comment by brandonpittman** [comment]
@lejtzen Thanks. Fixed it. 

https://www.npmjs.com/package/gridsome-plugin-svg/v/0.0.14

**Comment by lejtzen** [comment]
Wow, thats quick @brandonpittman! Thanks for a great plugin and for accepting the PR. Cheers!
